### ISSUE TITLE
35mm O-ring missing from BOM

### ISSUE THREAD

**Issue by terrag42** [bryancera/CERA-1#3]
What size o-ring goes between the "tube_endMount" and the "auger_stage"? This part is missing from the BOM. It looks to be about 35mm.

**Comment by bryancera** [comment]
It is a custom gasket, and is included in "DXF.zip".
It is made from the nitrile rubber sheet specified in the BOM.

**Comment by jeffnielson** [comment]
I'm using one of these from lowes which was in stock:
https://www.lowes.com/pd/Keeney-6-in-Rubber-Washer/1082955
It seems the same, but we'll see how it works long term.
